- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/index.js
- frontend/src/pages/EditPage.js
- frontend/src/pages/FollowerPage.js
- frontend/src/pages/FollowingPage.js
- frontend/src/pages/HomePage.js
- frontend/src/pages/LoginPage.js
- frontend/src/pages/MapPage.js
- frontend/src/pages/MyPage.js
- frontend/src/pages/NewPage.js
- frontend/src/pages/NotFoundPage.js
- frontend/src/pages/OthersPage.js
- frontend/src/pages/SignUpPage.js
components and pages added. App.js, index.js 수정
"/"를 통해 페이지 이동할 수 있도록 설정해둠
> components and pages added. App.js, index.js 수정

- .gitignore
> edited root .gitignore

- backend/requirements.txt
added cryptography to requirements.txt in backend
> added cryptography to requirements.txt in backend

- run.sh
> added starter script

- backend/requirements.txt
- backend/routers/keywordExt_router.py
made it server-deploy ready. Backend is now a single python package.
> added server-deplopy ready

- frontend/src/pages/LoginPage.css
- frontend/src/pages/RegisterPage.css
- frontend/src/pages/RegisterPage.js
수정:
LoginPage.css: 로그인버튼 색상 변경
RegisterPage.js: radio-gender className 추가
RegisterPage.css: radio의 accent-color 변경
> 0707 김태완 frontend 변경점

- backend/requirements.txt
- backend/routers/mysql_router.py
Default password is now mangoberry
> Implemented password checking. Default password is now 'mangoberry'

- README.md
- backend/routers/mysql_router.py
- frontend/src/pages/RegisterPage.css
- frontend/src/pages/RegisterPage.js
Connected user registeration page with backend api
> Added registeration

- frontend/src/pages/EditPage.css
- frontend/src/pages/EditPage.js
- frontend/src/pages/FollowingPage.css
- frontend/src/pages/FollowingPage.js
- frontend/src/pages/MyPage.css
- frontend/src/pages/MyPage.js
- frontend/src/pages/NewPage.css
- frontend/src/pages/NewPage.js
수정에 수정을 거처 오류를 해결하고 결국 올리는 데..
> 0710 오전 11:26 정민희 frontend

- frontend/src/App.js
- frontend/src/components/ProtectedRoute.js
- frontend/src/components/WelcomePopup.css
- frontend/src/components/WelcomePopup.js
- frontend/src/contexts/AuthContext.js
- frontend/src/pages/RegisterPage.js
생성:
- components/ProtectedRoute.js : 로그인이 안된 상태에서 들어가면 안되는 Route를 보호하기 위해 생성
수정:
- WelcomePopup.js : 
멘트 수정.('식당 3곳'이 아닌 '리뷰는 키워드 분석용으로 사용'으로 변경)
skip button 추가
- WelcomePopup.css : popup-page h3 삭제 후 popup-sub-title 생성.
- AuthContext.js :
이전에는 WelcomPopup창을 봤나 안봤나를 로컬에서만 관리를 해 다른 컴퓨터에서 로그인하면 뜨게 된다. 이 방식을 버리고 유저의 키워드가 없으면 뜨게하는 방식으로 변경 (아직 DB가 연결되지 않아 정상작동하는 지는 미정. 지금은 로그인 할 때마다 뜬다.)
- RegistgerPage.js : 이메일과 닉네임 칸 위치 변경
- App.js : /my, /new, /edit, /follower, /following에 ProtectedRoute를 적용
> 07010 김태완 frontend 변경점

- backend/routers/review.py
replaced user_review index to user_review_kor to use korean properly with nori tokenizer.
> Backend bk

- backend/requirements.txt
- backend/routers/mongo_router.py
- backend/routers/review.py
- backend/schemas/review.py
- Edited all three review APIs — POST, PUT, and DELETE.
- Changes in POST: Keywords retrieved from the review are now added to both the review_keywords and user_keywords collections in MongoDB.
- Changes in PUT: Keywords are updated in both review_keywords and user_keywords. Depending on the changes to the review, keywords may be added or removed.
- Changes in DELETE: Keyword counts are decremented in user_keywords, and any keyword with a frequency below 1 is removed. Keywords from the deleted review are also removed from review_keywords.
> Edited review APIs with keywords

- backend/routers/review_router.py
- backend/routers/review_search_router.py
- backend/scripts/reindexing.py
메인 페이지에서 통합 검색이 가능하게 review search 수정함.
기존 elasticsearch 리뷰 인덱스에 닉네임이 없어서, 새로운 index를 만들어 닉네임을 추가함.
> Edited review search function

- backend/main.py
- backend/scripts/post_review.py
- Cleaned router importing at main
- Added script that uploads review written by teammates to the database directly using the api.
> Minor update

- backend/routers/review_router.py
- backend/scripts/delete_review.py
Update review router had an error, and it has been fixed.
> fixed update review error

- backend/scripts/delete_review.py
Delete reviews with the review_id in range of 0 to 500.
> script for deleting all reviews

- backend/main.py
- backend/routers/review_router.py
- backend/routers/social_router.py
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/components/PostItem.js
- frontend/src/components/PostList.js
- frontend/src/components/WordCloud.js
- frontend/src/pages/MyPage.css
- frontend/src/pages/MyPage.js
- frontend/src/pages/OthersPage.css
- frontend/src/pages/OthersPage.js
Connected MyPage and OthersPage to backend api
- Edited PostList so that it receive user id to filter
- Implemented WordCloud for both pages
> Front back connection

- frontend/src/components/PostDetailModalContent.js
- frontend/src/components/PostItem.css
- frontend/src/components/PostList.css
- frontend/src/pages/EditPage.css
- frontend/src/pages/EditPage.js
- frontend/src/pages/HomePage.css
- frontend/src/pages/NewPage.css
- frontend/src/pages/NewPage.js
수정:
PostDetailModalContent.js: <RatingDisplay score={selectedPost.rating/10}>으로 변경
PostList.css: 
- .post-list-wrapper {padding: 0px;} 으로 변경
- .post-grid-container {padding: 0px; padding-top:10px}로 변경
- 화면 너비가 1200px이하면 2줄로 나오도록 변경
- 화면 너비가 784px이하면 1줄로 나오도록 변경
HomePage.css : 화면 너비가에 따라 양옆 마진 줄어들거나 제거.
PostItem.css : 게시물 비율을 1:2에서 1:1.2로 변경.
NewPage.js:
- 이미지 삭제 기능 추가
- 이미지 추가하는 영역과 추가된 이미지 미리보기 영역을 나눔: 이미지 삭제 버튼을 누를 때마다 사진이 새로 추가가 되어서 일단 바꿈
- 삭제 버튼 제거: 있을 필요가 없기에
NewPage.css: 
- .newpage-keyword-section{gap: 10px;  flex-wrap: wrap;} 추가   .keyword{} 제거> 적용되는 곳이 없음
- .action-buttons{margin-bottom: 20px;} 추가. 하단이 붙어있어서 좀 띄어놓음
- .image-preview{} 수정: 넣는 이미지 원본 크기 대로 나오도록
EditPage.js : 
- style={{ visibility: 'hidden' }} 제거 > 이거 때문에 삭제버튼이 보이지 않았다.
- 이미지 삭제 기능 추가
- 이미지 추가하는 영역과 추가된 이미지 미리보기 영역을 …
> 0721 김태완 frontend 변경점 오전

- frontend/src/pages/EditPage.js
- frontend/src/pages/NewPage.js
Now NewPage and EditPage actually uses user_Id
> Updated NewPage where useAuth were not working

- frontend/src/pages/EditPage.js
> Implemented Review Deletion

- frontend/src/pages/FollowerPage.js
- frontend/src/pages/FollowingPage.js
FollowingPage.js : RatingDisplay 추가
FollowerPage.js : RatingDisplay 추가
> ratingDisplay 추가

- backend/routers/keyword_router.py
- backend/routers/review_search_router.py
- backend/routers/social_router.py
- backend/services/s3.py
- frontend/src/components/PostDetailModalContent.js
- frontend/src/components/PostItem.js
- frontend/src/components/PostList.js
- frontend/src/components/WelcomePopup.js
- frontend/src/contexts/AuthContext.js
- frontend/src/pages/EditPage.js
- frontend/src/pages/FollowerPage.js
- frontend/src/pages/FollowingPage.js
- frontend/src/pages/MyPage.js
- frontend/src/pages/OthersPage.js
- Added Profile Picture Updating
- Added Compatibility score for follower/following api
- In process of implementing showing score
- WelcomePopup now shows if user have no keyword
- EditPage and NewPage now properly upload as user_id
- Profile picture properly load for all page
> Front back connect

- frontend/src/components/Header.css
- frontend/src/components/Header.js
- frontend/src/components/PostDetailModalContent.css
- frontend/src/pages/EditPage.css
- frontend/src/pages/EditPage.js
- frontend/src/pages/HomePage.css
- frontend/src/pages/MyPage.css
- frontend/src/pages/NewPage.css
- frontend/src/pages/NewPage.js
{ 0721 김태완 frontend 변경점 수업 이후 }
수정:
Header.js: 내 프로필 > 프로필, 새글쓰기 > 글쓰기 로 변경
Header.css : 화면 너비 360이하 일때 메뉴바 배치 변경, logo에 margin 제거
HomePage.css : 화면너비 360이하일 때 PostList 위치를 Header에 맞게 조정
MyPage.css : 화면너비 360이하일 때 맞춰 화면 구성 조정
NewPage..js : makepage로 되있던 것 전부 newpage로 변경
NewPage.css : 화면너비 360이하일 때 맞춰 화면 구성 조정, makepage로 되있던 것 전부 newpage로 변경
EditPage.js : makepage로 되있던 것 전부 editpage로 변경
EditPage.css : 화면너비 360이하일 때 맞춰 화면 구성 조정, makepage로 되있던 것 전부 editpage로 변경
> 0721 김태완 frontend 변경점 수업 이후

- backend/routers/keyword_router.py
- backend/schemas/review.py
- frontend/src/components/MapSidebar.css
- frontend/src/components/MapSidebar.js
- frontend/src/components/WelcomePopup.js
- frontend/src/pages/MapPage.js
- frontend/src/setupProxy.js
- Fixed initial boarding process
- Working on mappage connection
> Sidebar comp

- frontend/src/pages/AddRestaurantPage.css
- frontend/src/pages/AddRestaurantPage.js
- frontend/src/pages/EditPage.js
- frontend/src/pages/NewPage.js
- frontend/src/setupProxy.js
- 식당 추가 페이지 모바일환경 고침
- 식당 추가페이지 글쓰기/수정에서 들어갈수 있도록 수정
> New restaurant fix

- frontend/src/pages/FollowerPage.css
- frontend/src/pages/FollowerPage.js
- frontend/src/pages/FollowingPage.css
- frontend/src/pages/FollowingPage.js
-following, follower page; 700px 모바일 화면 내에서 화면 및 박스 안 요소들 깨지지 않도록 
-following, follower page; 프로필 닉네임 옆 꼬리 아이콘과 % 올바른 위치에 크기 조절해서 삽입
> following, follower page 수정

- frontend/src/components/Header.js
- frontend/src/components/PostItem.css
- frontend/src/components/PostItem.js
- frontend/src/components/RatingDisplay.js
- frontend/src/pages/AddRestaurantPage.css
- frontend/src/pages/FollowerPage.css
- frontend/src/pages/FollowerPage.js
- frontend/src/pages/FollowingPage.css
- frontend/src/pages/FollowingPage.js
- frontend/src/pages/MapPage.js
- frontend/src/pages/RestaurantInfoPage.css
- frontend/src/pages/RestaurantInfoPage.js
PostItem.js : post-title h4에서 p로 변경
PostItem.css : post-title bold 제거
Header.js : 프로필 > 내 프로필 변경
FollowerPage.js : 뒤로가기 버튼 추가
FollowerPage.css :  뒤로가기 버튼 추가
FollowingPage.js :  뒤로가기 버튼 추가
FollowingPage.css :  뒤로가기 버튼 추가
AddRestaurantPage.css : 화면 너비 700px이하 일 때 화면 제대로 보이도록 수정
RatingDisplay.js : score가 10과 11사이에 소수점으로 10.xx로 나오면 꼬리가 표시 안되는 것을 수정. 한쪽에 =을 제거
RestaurantInfoPage.js : 식당 대표 이미지 없을 때 뜨는 문구 제거. 식당의 리뷰 문구 추가. 북마크 버튼 추가(추후에 스크린샷만 따서 삭제할 예정)
RestaurantInfoPage.css : 좌측과 우측 구분선 생성.
MapPage.js : 모바일 환경에서의 탐색 버튼 문구 검색으로 변경
> 0723 김태완 frontend 변경점 오후 2

- backend/routers/restaurant_router.py
- frontend/public/index.html
- frontend/src/pages/MapPage.js
- frontend/src/pages/NewPage.js
- frontend/src/setupProxy.js
- Fixed NewPage
- Added Mapmarker as Foxtail and add color gradiant
> Map marker

- frontend/src/components/WordCloud.js
- frontend/src/pages/EditPage.css
- frontend/src/pages/FollowerPage.js
- frontend/src/pages/FollowingPage.js
- frontend/src/pages/NewPage.css
- frontend/src/pages/RestaurantInfoPage.css
- frontend/src/pages/RestaurantInfoPage.js
수정:
WordCloud.js : 키워드 글자 정방향을 나오도록 수정
FollowerPage.js : 뒤로가기 아이콘 변경
FollowingPage.js : 뒤로가기 아이콘 변경
NewPage.css : 사진 영역 border 설정
EditPage.css : 사진 영역 border 설정
RestaurantInfoPage.js : 뒤로가기 아이콘 변경. bookmark 임시로 해둠
RestaurantInfoPage.css : bookmark 임시로 해둠
> 0724 김태완 frontend 변경점 오전

- frontend/src/pages/AddRestaurantPage.css
- frontend/src/pages/AddRestaurantPage.js
- frontend/src/pages/EditPage.css
- frontend/src/pages/EditPage.js
- frontend/src/pages/NewPage.css
- frontend/src/pages/NewPage.js
수정:
NewPage.js : 식당 검색 개수 10으로 변경
NewPage.css : 화면 너비 700px이하일 때 사진 세로방향으로 들어가도록 변경
EditPage.js : 식당 검색 개수 10으로 변경
EditPage.css : 화면 너비 700px이하일 때 사진 세로방향으로 들어가도록 변경
AddRestaurantPage.js : 문구 변경
AddRestaurantPage.css : 왼쪽정렬로 변경
> 0724 김태완 frontend 변경점 오후

- frontend/src/pages/HomePage.css
- frontend/src/pages/MapPage.css
- frontend/src/pages/MapPage.js
Homepage.css : 전체, 팔로잉 색상 변경
MapPage.js: 로딩 모양 변경.  탐색버튼 모바일에서 보이게 함(아직 모름)
MapPage.css: 탐색버튼 모바일에서 보이게 함(아직 모름)
> 0725 김태완 frontend 변경점 오전

- frontend/src/pages/MapPage.css
- frontend/src/pages/MapPage.js
> 탐색버튼 위치 조정
